name: CI<!doctype html>
<html>
<head>
<meta charset="utf-8">
	
	<!--文字コードの種類としてUTF-8を指定します-->

 <title>MAKE::VR#01 11月19日(日) SHIBUYAで開催！</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta name="Description" content="MAKE::VR#01 11月19日(日) SHIBUYAで開催！日々変化していくクリエイティブシーンの情報をインプットし、あらたな化学変化を起こすことを目的に、毎月業界の一線で活躍しているゲストをお招きして、お話を伺う勉強会です。">
    <meta property="og:title" content="MAKE::VR#01 11月19日(日) SHIBUYAで開催！">
    <meta property="og:description" content="MAKE::VR#01 11月19日(日) SHIBUYAで開催！日々変化していくクリエイティブシーンの情報をインプットし、あらたな化学変化を起こすことを目的に、毎月業界の一線で活躍しているゲストをお招きして、お話を伺う勉強会です。">
    <meta property="og:type" content="Website">
    <meta property="og:url" content="#">
    <meta property="site_name" content="MAKE::VR#01 11月19日(日) SHIBUYAで開催！">
    <meta property="og:image" content="images/meta/og-image.png">
    <meta name="format-detection" content="telephone=no">
    <link rel="canonical" href="#">
    <link rel="apple-touch-icon" href="images/meta/touch-icon.png">
    <link rel="shortcut icon" href="images/meta/favicon.ico">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	
	
	
	<link rel="stylesheet" href="makeVR/css/reset.css">
	<link rel="stylesheet" href="makeVR/css/style.kadai.css">
	
</head>

<body>
	<!--body タグ内にはWebブラウザに表示させる内容が入る-->
	<!--以降の内容については基本的にbodyタグの内側に記述をしていきます-->
	<!--まずは、テキストデータをbodyタグの内側に貼り付けて、スタートします。vvv-->
	<header>
		<div class="main_visual">
		<h1>	
			<p>
				<img class="rogo" src="makeVR/images/header/kv_logo.png" alt="ロゴ">
				<img class="pc" src="makeVR/images/header/kv_text.png" alt="パソコン用の画像">
				<img class="sp" src="makeVR/images/header/kv_text__sp.png" alt="スマホ用の画像">
			</p>
		</h1>
	 </div>
	</header>
	
	<section class="consept">
		<h2>CONSEPT</h2>
		
		<p>MAKE::VRは、日々変化していくクリエイティブシーンの情報をインプットし、あらたな化学変化を起こすことを目的に、毎月業界の一線で活躍しているゲストをお招きして、お話を伺う勉強会です。 元々社内向けに行っておりましたが、同じクリエイティブシーンで活動するクリエイターのみなさまにも開放することで、お互いに出会い、意見を共有し、高めあっていける“場”にして行きたいと思っています。
		</p>
	
	</section>
	
	<section class="guest">
		<h2>GUEST</h2>
		<div class="guest-text">
			<h3>VR/AR STUDIO CEO/Creator 今野 現 氏</h3>
			<p>カーネギーメロン大学にて医学(眼科)とコンピューターサイエンスの博士を取得し、 米国のアートスタジオなどで活躍した後、2013年 VR/AR STUDIOを設立。

			現在国内外のコンサート・広告・アートフェスティバル等で上映するVR・ARの作品を数々手がける。 
			日本VR学会理事、 米 Artist of CompterScience 会員
			</p>
		</div>
	
	</section>

	<section class="schedule">
		<h2>SCHEDULE</h2>
		<div class="schedule-text">
		<p>2017年11月19日(日曜日) 19時〜22時</p>
			<dl>
				<dt>1部(19時〜20時)</dt>
				<dd>今野氏講演</dd>

				<dt>2部(20時15分〜22時)</dt>
				<dd>懇親会(軽食とアルコール・ソフトドリンクをご用意しております)</dd>

			</dl>
		</div>
		<p>
			<img class="pc" src="makeVR/images/schedule/schedule_img.jpg" alt="パソコン用の画像">
			<img class="sp" src="makeVR/images/schedule/schedule_img__sp.jpg" alt="スマホ用の画像">
		
		</p>

	</section>

	<section class="access">
		<h2>ACCESS</h2>
		<p>150-0002 東京都渋谷区渋谷１丁目23-21<br>
		渋谷キャスト2F<br>
		RCU DESIGN</p>
		
		<div class="maps">
			<iframe class="maps" src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d3241.5843968865815!2d139.70051981525825!3d35.66260988019864!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sshibuya+cast!5e0!3m2!1sja!2sjp!4v1507962524283" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
		</div>
	
	</section>

	<section class="entry-tool">
		<h2>ENTRY</h2>
		<div class="entry-text">
				<dl class="entry-text-top">
					<dt>参加費</dt>
					<dd>無料</dd>
					<dl>参加条件</dl>
					<dd>クリエイティブを仕事にしている方 または企業のご担当者様(御名刺を複数枚ご用意ください)
					</dd>	
				</dl>

				<form action="" method="POST">
					<!--formの中身をここに記入-->
					<ul>
						<li>
							<label for="name">お名前</label><br>
								<input class="name-box" type="text" name="name" id="name">
							</li>
						</ul>




						<ul class="radio-all">
						  	<li class="radio-title">職業</li>
								<li class="r1"><input class="radio-choice-1" type="radio" id="radio-choice-1" name="radeio-choice" checked value="1">
								<label for="radio-choice-1" class="sample_label">会社員</label>
								</li>
								<li class="r2">
								<input class="radio-choice-2" type="radio" id="radio-choice-2" name="radeio-choice" value="2">
								<label for="radio-choice-2" class="sample_label">会社経営</label>
								</li>
							  <li>
								<input class="radio-choice-3" type="radio" id="radio-choice-3" name="radeio-choice" value="3">
								<label for="radio-choice-3" class="sample_label">会社員</label>
								</li>
							

						</ul>
					
						<dl>
							<dd class="mail">
							<label for="mail">メールアドレス</label><br>
								<input class="mail-box" type="text" name="mail" id="mail">

							</dd>
						</dl>
					<div class="button1">
					<button class="button3" type="submit">entry</button>
					</div>

				</form>
			</div>
		
	
	</section>

	<footer>
		
			<p><img class="pc" src="makeVR/images/footer/footer_logo.png" alt="logo"></p>
			<p><img class="sp" src="makeVR/images/footer/kv_logo_sq.png" alt="sp-logo"></p>
		<small>
			<p>2F 21-23-1 Shibuya, Shibuya-ku,<br>
Tokyo, Japan,150-0002<br>
150-0002 東京都渋谷区渋谷1丁目23-21<br>渋谷キャスト2F</p>
	 		<p class="company">&copy;copyright RCU DESIGN Inc. All Right Reserved</p>	
		
		</small>
	
	</footer>
	
</body>
</html>


